INSERT INTO USER_PROFILE(emailId,PASSWORD,STATUS) VALUES ("xyz","$2a$10$JAs.w36Ij6Wp1mrfPXgq8uLB2yVFZHXXNR6cKygNvchzc1JcArTJq",1);

INSERT INTO USER_PROFILE(emailId,PASSWORD,STATUS) VALUES ("xyz","$2a$10$JAs.w36Ij6Wp1mrfPXgq8uLB2yVFZHXXNR6cKygNvchzc1JcArTJq",1);
